### ISSUE TITLE
Generator isn't seeded

### ISSUE THREAD

**Issue by liranbg** [mvayngrib/react-native-randombytes#3]
Hey,

I get an error while using react-native-randombytes with react-native@0.21

When I'm using it in debugging mode it works perfectly but I get this error while using in regular

![screenshot 2016-03-15 16 55 00](https://cloud.githubusercontent.com/assets/6547459/13782164/bd8ce4ee-eace-11e5-8b8b-84918dfad253.png)

*it fails within this line
let randomBytes = sjcl.random.randomWords(wordCount, 10)

**Comment by mvayngrib** [comment]
@liranbg interesting, which path does it take through the `init()` function? Does it manage to use `RNRandomBytes.seed`?

**Comment by trave7er** [comment]
@liranbg when you are using it in debug mode, do you mean Chrome? because Chrome is running V8 engine. and you are actually running js code on top of V8 (if I remember it correctly). I think the async version of randomBytes will still work, only the synchronous version is impacted.

**Comment by mvayngrib** [comment]
@liranbg @trave7er the sync version takes some effort to get working. If you can use async, use react-native-randombytes@^1

however, the sync version does work. I use [rn-nodeify](https://github.com/mvayngrib/rn-nodeify) to get it working, a node core shimmer for your top lever project. See an example project demoing the sync functionality: https://github.com/mvayngrib/randombytestest

because sjcl tries to pull in crypto, and crypto pulls in stream, and so on, you end up needing to shim quite a few of the node core libraries. See the postinstall script in the package.json in the linked project

**Comment by trave7er** [comment]
@mvayngrib wow, that is amazing, I didn't know we could do that. 👍

**Comment by mvayngrib** [comment]
@trave7er thx :)

**Comment by liranbg** [comment]
@trave7er & @mvayngrib thanks
