### ISSUE TITLE
installing and importing the library causes react-native issue 4968

### ISSUE THREAD

**Issue by orhanmaden** [mvayngrib/react-native-randombytes#5]
I tried all the solutions suggested at https://github.com/facebook/react-native/issues/4968.

I also verified that other libraries like lodash and bluebird are installed and imported as expected.

command line
`
npm i --save react-native-crypto
`

index.ios.js
`
import crypto from 'react-native-crypto'
`

Any suggestions are well appreciated.

**Comment by mvayngrib** [comment]
if you're using react-native-crypto, you'll need to use [rn-nodeify](https://github.com/mvayngrib/rn-nodeify) to hack the package.json files in your dependency tree until react-native acquires a [resolve.alias feature](https://productpains.com/post/react-native/packager-support-resolvealias-ala-webpack/)

you'll end up doing something like this:

```bash
npm i --save-dev rn-nodeify
# install crypto shim, use any necessary package-specific hacks (see rn-nodeify for details)
./node_modules/.bin/rn-nodeify --install crypto --hack
# the above line usually goes in my package.json "postinstall" script
```

it's not well documented as you can tell, mostly because not many people other than [vespakoen](https://github.com/vespakoen) and myself seem to care about creating a node-like environment in react-native...also it's an inglorious bunch of hacks :)

**Comment by orhanmaden** [comment]
Great! I got this part working thanks to your reply.

I did:
1. npm i --save-dev rn-nodeify
2. rn-nodeify --install --hack
3. linked to react-native-randombytes

Now I can import react-native-crypto. 

My actual goal is to use sjcl. In the index.js file of the react-native-randombytes that sjcl is required and used. Via console.log statements I validated that sjcl is initialized in that file.

When I require sjcl in my index.ios.js I get the react-native red screen of death (https://github.com/facebook/react-native/issues/4968) stating 'crypto' can't be found.

What am I missing? Why is the sjcl library initialized in react-native-randombytes and not in my index.ios.js?

Any suggestions are well appreciated.

**Comment by mvayngrib** [comment]
@orhanmaden i think this is mostly due to how require resolves dependencies. If you want to use sjcl in index.ios.js, you need to install sjcl directly:

```bash
npm i --save sjcl
# every time you install a new dep, rerun rn-nodeify
rn-nodeify --install --hack
```

**Comment by orhanmaden** [comment]
Thanks, that was the solution. It works now. 

rn-nodeify is a great ~~hack~~ package. :-).

**Comment by mvayngrib** [comment]
@orhanmaden glad you got it working :)
